
## Autoload completions and prompts ##

# Extend completion path locally
fpath=(~/.zsh/functions $fpath) 

# Load everything
autoload -Uz compinit promptinit vcs_info colors
compinit
promptinit
colors

zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats "(%{$fg[blue]%}%b%{$reset_color%})"
precmd() {
   vcs_info
}

# Set prompt
setopt prompt_subst

NEWLINE=$'\n'
PROMPT='%{$fg[red]%}%n%{$reset_color%} on %{$fg[blue]%}%m%{$reset_color%} in %{$fg[magenta]%}%~%{$reset_color%} ${vcs_info_msg_0_}${NEWLINE}'
RPROMPT=''

# Set ViM mode
bindkey -v

## History ##
export HISTSIZE=200000
export HISTFILE="$HOME/.history"
export SAVEHIST=$HISTSIZE

setopt hist_ignore_all_dups

## Aliases ##

# Get to this file faster
alias zshrc='vi ~/.zshrc'

# ls
alias ls='ls -G'
alias l='ls -lFhG'
alias ll='ls -lG'

# tail
alias t='tail -f'

# Better grep
alias grep='grep --color'

# Force vi to alias the most specific vim on path
alias vi=vim

# For faster cd navigation
alias -g ..='../'
alias -g ...='../../'
alias -g ....='../../../'
alias -g .....='../../../../'

# todo list
alias todo='vim $HOME/notes/todo.md'

# Copy as rsync
alias cpv="rsync -poghb --backup-dir=/tmp/rsync -e /dev/null --progress --"

# Syntax Highlighting
if [ -e /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]
then 
   source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

if [ -e /usr/local/share/zsh/site-functions/_aws ]
then 
   source /usr/local/share/zsh/site-functions/_aws
fi

# Set up Homebrew path
export PATH="/usr/local/bin:$PATH"

# Set up rbenv path
if command -v rbenv > /dev/null
then
   export PATH="$HOME/.rbenv/shims:$PATH"
fi

if command -v pyenv > /dev/null
then
   export PATH="$(pyenv root)/shims:$PATH"
fi

# Golang
export GOPATH=/workplace/golang
export PATH=$PATH:$GOPATH/bin

# Rust
export PATH=$PATH:$HOME/.cargo/bin
