#!/bin/zsh

# move ourselves into the scripts directory
canonical="$PWD"

# Defaults
ZSH_PATH=/usr/local/bin/zsh


# Try and install xcode if necessary
if xcode-select -p &> /dev/null
then
   print "XCode CLI tools already installed, skipping"
else
   print "Installing XCode CLI..."
   xcode-select --install
fi

# Install homebrew, and check the path
if command -v brew &> /dev/null
then
   print "Homebrew already installed, cleaning..."
   brew uninstall --force `brew list`
else
   print "Installing Homebrew"
   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   brew update
fi

# Install Homebrew packages
brew tap Homebrew/bundle
brew bundle

# Set up zsh
if ! grep "$ZSH_PATH" /etc/shells &> /dev/null
then
   print "Appending zsh [$ZSH_PATH] to approved shell list (Password Required)..."
   printf "/usr/local/bin/zsh" | sudo tee -a /etc/shells &> /dev/null
fi

if [ $SHELL != $ZSH_PATH ]
then
   print "Setting Homebrew zsh [$ZSH_PATH] to default shell (Password Required)..."
   chsh -u $USER -s $ZSH_PATH
fi

print "Linking dotfiles..."
echo $HOME
ln -sf $canonical/dotfiles/gitconfig $HOME/.gitconfig
ln -sf $canonical/dotfiles/vim $HOME/.vim
ln -sf $canonical/dotfiles/vimrc $HOME/.vimrc
ln -sf $canonical/dotfiles/vimrc.bundles $HOME/.vimrc.bundles
ln -sf $canonical/dotfiles/zshrc $HOME/.zshrc
ln -sf $canonical/dotfiles/zsh $HOME/.zsh

# Set up vim
# print "Generating neobundle..."
# curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh
vim +NeoBundleInstall +qall

# Open the best terminal in the world
open /Applications/iTerm.app
